### ISSUE TITLE
rblog() causes extremely low FPS when running on normal magnetic HDD (non-SSD)

### ISSUE THREAD

**Issue by CecilHarvey** [Fundynamic/RealBot#13]
as title.

video:
https://youtu.be/5g2ZyasCHQc

I profiled a bit with Instruments tool included with xcode, and found that rblog() (which writes a lot of log messages to reallog.txt) caused problem:
![screen shot 2018-09-05 at 10 25 25 pm](https://user-images.githubusercontent.com/1220443/45099745-a0568d80-b15a-11e8-9353-d3359d151057.png)

possible solution:
only open the reallog.txt file once, and close it when program exits.

**Comment by stefanhendriks** [comment]
nice find. I saw that video and noticed that stuttering - not good.

Maybe you can explain to me some time how you run XCode Instruments with RealBot? It would be helpful for me to debug and see myself. (Now I use CLion from Jetbrains and run `make` from cmd line).

One thing though about this issue. `rblog` always opened file and such. One thing I change recently is added a `printf` in that function. Perhaps *that* causes the stuttering? Or did you also have the stuttering on the 'older' versions of RealBot? (ie build 30xx?)

**Comment by CecilHarvey** [comment]
the above screenshot already shown that the problem is caused by fopen()/fclose() (under cBot::setGoalNode() call). printf() does not take much time there.

will write something about how to use Instruments tool later when I have the time.

**Comment by stefanhendriks** [comment]
Sure thing. I already started working on this in between work ;-)

**Comment by stefanhendriks** [comment]
i had some left-over changes. Pushed it regarding this. Basically it opens the file once (on startup). Unfortunately I could not find a quick way to close the file at the right moment.

**Comment by stefanhendriks** [comment]
@CecilHarvey let me know if you need a binary or you could compile it yourself. I suppose the latter since you managed to get it working on your mac ;-)

**Comment by stefanhendriks** [comment]
Do note, latest commits (after d566476) have by default logging enabled (debug messages), which spam your log file. So do not use that.

**Comment by CecilHarvey** [comment]
sorry for late reply

I tested commit d566476 under Fedora GNU/Linux (as latest version of xcode no longer supports compiling for 32-bit), and fps is good.

**Comment by stefanhendriks** [comment]
no probs. 

Too bad about macOS, I am still on Sierra, so I'm still good I guess.

**Comment by APGRoboCop** [comment]
Yes well that Mac OS X Catalina is bloody ridiculous along with Apples overpriced computers and phones. So you maybe best off ignoring macOS for the future...

**Comment by stefanhendriks** [comment]
@CecilHarvey instead of open/close, i use `fflush` now. All is well, you can use the latest commit now if you want.
