### ISSUE TITLE
Bots get stuck into other bots

### ISSUE THREAD

**Issue by stefanhendriks** [Fundynamic/RealBot#22]
Related to #17 - bots who seem to get very close to each other get stuck. Not sure if it is because of the bot logic itself or that the client logic (Fake clients) causes them to get stuck easily.

Whatever the case, this interrupts any logical conclusion we can make for #17 because if the bot is getting stuck because of another bot then this means we can't conclude the connection is wrong.

Several things should be done:
- avoid other bots at all times
  - ie perhaps scan in a radius where other bots are and try to move away from bots. The ideal angle would be towards the next node, but if other players are in the way try to move away from them (and update allowance timer for reaching other node).
- if the node to head for is occupied by a player (bot or not) try to find a node that is not occupied and still goes to the node after. So we can sort of diverge our path without recalculating it entirely.

Screenshots:
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/1332066/64837237-cd4f4300-d5ed-11e9-8c88-986688d4b251.png">

**Comment by jeefo** [comment]
Hello.

You just need to comment out those lines:
    (*g_engfuncs.pfnSetClientKeyValue)(clientIndex, infobuffer, "cl_lw", "1");
    (*g_engfuncs.pfnSetClientKeyValue)(clientIndex, infobuffer, "cl_lc", "1");

To get this issue fixed.

**Comment by stefanhendriks** [comment]
Really? I'm going to try that right now...

**Comment by stefanhendriks** [comment]
Thank you @jeefo

Funny thing is, this has been bugging me for over 15 years if not more.
Not sure you know this was it, but I am very grateful you mentioned this
to me.

Thanks again
