### ISSUE TITLE
[r3073] Bots wont diffuse/plant bomb

### ISSUE THREAD

**Issue by APGRoboCop** [Fundynamic/RealBot#7]
> Bots wont diffuse/plant bomb, bots kill 1 bot team mate (1 in T 1 in CT), 1 random bot camp in base sometimes stuck
> 
> Tested with the ff:
> HL 1.1.0.4~HL 1.1.2.2/CS1.0~1.6
> MetaMOD/Steam/Non-Steam/Working
> 

http://forums.bots-united.com/showthread.php?p=66803#post66803

**Comment by stefanhendriks** [comment]
I saw on the forum post it worked again?

I was going through the code about bomb planting and defusion. Its a mess really. I did some testing and it looks like bots often find planted bombs and try to defuse them. I cleaned up a bit of code around that recently, maybe that helped (although I did not really change much behavior I think).

**Comment by stefanhendriks** [comment]
I recently saw this working, although I am refactoring the code, I keep an eye on this. Closing this.
